<?php

declare(strict_types=1);

namespace App\Http\Controllers\Api\v1;

use App\Actions\User\CreateUserAction;
use App\Actions\User\ListUsersAction;
use App\Http\Controllers\Controller;
use App\Http\Requests\v1\Users\StoreUserRequest;
use App\Http\Requests\v1\Users\UpdateUserRequest;
use App\Http\Requests\v1\Users\UsersRequest;
use App\Http\Resources\v1\UserResource;
use App\Models\User;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Http\JsonResponse;
use Throwable;

/**
 * Users API controller.
 *
 * @author Generated by Laravel Modular
 *
 * @since 2026-01-05
 */
final class UsersController extends Controller
{
    use AuthorizesRequests;

    /**
     * Display a listing of the resource.
     */
    public function index(UsersRequest $request, ListUsersAction $listUsersAction): JsonResponse
    {
        $this->authorize('users.view');

        $users = $listUsersAction->handle($request->validated());

        return $this->successResponse(UserResource::collection($users));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @throws Throwable
     */
    public function store(StoreUserRequest $request, CreateUserAction $createUserAction): JsonResponse
    {
        $this->authorize('users.create');

        $user = $createUserAction->handle($request->validated());

        return $this->createdResponse(new UserResource($user), 'user');
    }

    /**
     * Display the specified resource.
     */
    public function show(User $user): JsonResponse
    {
        $this->authorize('users.view');

        return $this->successResponse(new UserResource($user));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateUserRequest $request, User $user): JsonResponse
    {
        $this->authorize('users.update');

        $data = $request->validated();

        if (isset($data['role'])) {
            $user->syncRoles([$data['role']]);
            unset($data['role']);
        }

        $user->update($data);

        return $this->updatedResponse(new UserResource($user), 'user');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(User $user): JsonResponse
    {
        $this->authorize('users.delete');

        $user->delete();

        return $this->deletedResponse('user');
    }
}
