<?php

declare(strict_types=1);

namespace App\Http\Requests\v1\Users;

use Illuminate\Foundation\Http\FormRequest;

/**
 * Users form request.
 *
 * @author Generated by Laravel Modular
 *
 * @since 2026-01-05
 */
final class UsersRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @queryParam search string Filter by name or email. Example: John
     * @queryParam role string Filter by role name. Example: Employee
     * @queryParam is_active boolean Filter by active status. Example: true
     *
     * @return array<string, mixed>
     */
    public function rules(): array
    {
        return [
            'search' => ['nullable', 'string', 'max:255'],
            'role' => ['nullable', 'string', 'max:255'],
            'is_active' => ['nullable', 'boolean'],
        ];
    }

    /**
     * Get custom messages for validator errors.
     *
     * @return array<string, string>
     */
    public function messages(): array
    {
        return [
            // Add your custom messages here
        ];
    }

    /**
     * Get custom attributes for validator errors.
     *
     * @return array<string, string>
     */
    public function attributes(): array
    {
        return [
            // Add your custom attributes here
        ];
    }
}
